### ISSUE TITLE
Image Data

### ISSUE THREAD

**Issue by Zacharys-Hackery** [NadhirBoukhenifra/ACPWOTP#1]
Hello,

Looking for a simplified, One-Time Pad project on GitHub, I stumbled across your project, which really is practical, with great documentation! I would be more than happy to give you recognition for this amazing work.

Anyhow, in trying to minimize the amount of code I would like to use, I came across the huge image functions you have written. It stumbled me a bit because isn't image data in binary? If that is the case, then you can just alter the information with binary and unicode similar to the way you would do it with plain text.

P.S.: _You really should add a license to this program. You wouldn't want to lose credit to this!_

**Comment by NadhirBoukhenifra** [comment]
Hello,

Thank you for your opinion :)

About Image, First, I Transform colored image to Grey then to Black/White, just for education purpose.

I will try to update this project to deal with binary data directly :)

1. Read image in binary mode.
2. Generate random key with same length of image binary code.
3. Use XOR with the image binary data and the new key.
4. Generate new image.

To decrypt: the same way - but we must have the key.

Thank you for you Tip
